theme: jekyll-theme-minimal
title: Ilan Cerna-Turoff
description: I am an epidemiologist who examines social and environmental aspects of health. I currently am a NIEHS T32 Postdoctoral Fellow at Columbia University’s Mailman School of Public Health.<br>
</div>
    <a href="https://www.researchgate.net/profile/Ilan-Cerna-Turoff">ResearchGate</a> <br>
    <a href="https://www.linkedin.com/in/ilancernaturoff/">LinkedIn</a> <br>
    <a href="https://orcid.org/0000-0002-0787-9068">ORCID</a> <br>
