theme: jekyll-theme-minimal
title: Ilan Cerna-Turoff
description: I am an epidemiologist who examines social and environmental aspects of health. I currently am a NIEHS T32 Postdoctoral Fellow at Columbia University’s Mailman School of Public Health.

[ResearchGate](https://www.researchgate.net/profile/Ilan-Cerna-Turoff)
[LinkedIn](https://www.linkedin.com/in/ilancernaturoff/) 
[ORCID](https://orcid.org/0000-0002-0787-9068) 
