name: "ilan-website"
theme: jekyll-theme-minimal
title: Ilan Cerna-Turoff
description: I am an epidemiologist who examines social and environmental aspects of health. I currently am a NIEHS T32 Postdoctoral Fellow at Columbia University’s Mailman School of Public Health.
output_dir: "."
navbar:
  title: "Home"
  left:
    - text: "Current Projects"
      href: about.html
    - text: "Publications"
      href: publications.html
    - text: "Personal"
      href: personal.html
    - icon: fa-envelope fa-lg
      href: mailto:<it2208@caa.columbia.edu>
    - icon: fa-github fa-lg
      href: https://github.com/ilan-cerna-turoff

output:
  html_document:
    theme: sandstone
    css: style2.css
